### ISSUE TITLE
After latest updates gpu-configuration is not working properly

### ISSUE THREAD

**Issue by troydm** [Sabayon/sabayon-live#2]
After latest equo update following function is not working anymore

    @staticmethod
    def check_if_driver_is_available(xdriver):
        drv_path = "/usr/lib/xorg/modules/drivers/" + xdriver + "_drv.so"
        if os.path.isfile(drv_path):
            print("check_if_driver_is_available for " + xdriver + ": available")
            return True
        print("check_if_driver_is_available for " + xdriver + ": not available")
        return False
 
"/usr/lib/xorg/modules/drivers/" is not correct path to modules, changing it to 
"/usr/lib64/xorg/modules/drivers/" makes gpu-configuration work properly

**Comment by joostruis** [comment]
This has been fixed.
https://github.com/Sabayon/sabayon-live/commit/dacf4902260023509b44b7008865d9ebb2633806
